1. Импортируйте пакет numpy под именем np

In [2]:
import numpy as np

2. Распечатайте версию numpy

In [2]:
print(np.__version__)

1.26.4


3. Создайте вектор со значениями от 10 до 49 

In [5]:
vector = np.arange(10, 50, 1)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Перевернуть вектор (первый элемент становится последним)

In [15]:
vector = np.arange(10, 50, 1)
print(vector)
print(vector[::-1])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


5. Создайте массив 5x5 со случайными значениями и найдите среднее значение и медиану для каждой строки

In [20]:
A = np.random.random((5,5))
print(A)
print("=====")
sr_znach = np.mean(A, axis=1)
median = np.median(A, axis=1)
print(sr_znach)
print("=====")
print(median)

[[0.23212549 0.46635181 0.06139273 0.46536321 0.68648467]
 [0.67982181 0.52149072 0.71338948 0.75078001 0.22243998]
 [0.27279788 0.57969788 0.25696091 0.24407401 0.7717782 ]
 [0.9488586  0.54462986 0.51618121 0.04941923 0.21915387]
 [0.62079141 0.42171011 0.51321304 0.91474055 0.14177736]]
=====
[0.38234358 0.5775844  0.42506177 0.45564855 0.5224465 ]
=====
[0.46536321 0.67982181 0.27279788 0.51618121 0.51321304]


6. Преобразуйте одномерный массив из 27 элементов целого типа в трехмерный (3x3x3)

In [25]:
a = np.array([x for x in range(27)])
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [24]:
b = a.reshape((3,3,3))
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


7. Преобразуйте все элементы массива numpy из типа данных float в integer

In [29]:
a = np.array([[3.5, 1.9, 8.45], [4.7, 7.9, 1.9]])
print(a)

[[3.5  1.9  8.45]
 [4.7  7.9  1.9 ]]


In [30]:
b = a.astype(int)
print(b)

[[3 1 8]
 [4 7 1]]


8. Преобразуйте двоичный массив numpy [[1, 0, 0], [1, 1, 1],  [0, 0, 1]] (содержащий только 0 и 1) в логический массив numpy

In [33]:
a = np.array([[1, 0, 0], [1, 1, 1],  [0, 0, 1]])
print(a)

[[1 0 0]
 [1 1 1]
 [0 0 1]]


In [34]:
b = a.astype(bool)
print(b)

[[ True False False]
 [ True  True  True]
 [False False  True]]


9. Расположите 2 массива numpy горизонтально (hstack), т.е. 2 массива, имеющих одинаковое 1-е измерение (количество строк в 2D-массивах)

In [38]:
a1 = np.array([[1,2,3], [4,5,6]])
a2 = np.array([[7,8,9], [10,11,12]])

In [40]:
a3 = np.hstack((a1, a2))
print(a3)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


10. Расположите 2 массива numpy вертикально (vstack), т.е. 2 массива, имеющие одинаковое последнее измерение (количество столбцов в 2D-массивах)

In [35]:
a1 = np.array([[1,2],
 [3,4],
 [5,6]])

a2 = np.array([[7,8],
 [9,10],
 [10,11]])

In [37]:
a3 = np.vstack((a1, a2))
print(a3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


11. Из 2 массивов numpy извлеките индексы, в которых совпадают элементы (np.where)

In [41]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])

In [45]:
c = np.where(a == b)
print(c)

(array([0, 3, 4], dtype=int64),)


12. Выведите результат умножения 2 матриц (в виде массива numpy)

In [49]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

b = np.array([[2,3,4], 
 [5,6,7], 
 [8,9,10]])

In [50]:
c = np.dot(a,b)
print(c)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


13. Выведите транспонированную матрицу

In [59]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
t = np.transpose(a)
print(t)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


14. Вычислите синус массива углов (в радианах) с помощью NumPy

In [128]:
angles = np.array([3.14, 3.14/2, 6.28])
print(angles)

[3.14 1.57 6.28]


15. Отсортировать вектор

In [71]:
v = np.random.random(size=[10])
print(v)

[0.98814807 0.45145542 0.30674149 0.95975706 0.57814437 0.94697656
 0.53232802 0.63624753 0.44027832 0.80622364]


In [72]:
sorti = np.sort(v)
print(sorti)

[0.30674149 0.44027832 0.45145542 0.53232802 0.57814437 0.63624753
 0.80622364 0.94697656 0.95975706 0.98814807]


16. Проверить, одинаковы ли два NumPy массива

In [133]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

In [134]:
c = np.array_equal(a,b)
print(c)

True


17. В одномерном массиве заменить максимальный элемент на ноль

In [93]:
Z = np.random.random(10)

In [101]:
print(Z)

[0.65831232 0.97715073 0.940277   0.31231885 0.57592682 0.99838719
 0.93001088 0.04328497 0.55466374 0.93997321]


In [103]:
maxel = np.argmax(Z)
print(maxel)
Z[maxel] = 0
print(Z)

5
[0.65831232 0.97715073 0.940277   0.31231885 0.57592682 0.
 0.93001088 0.04328497 0.55466374 0.93997321]


18. Замените все нечетные числа одномерного массива на -1.

In [114]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [113]:
arr = np.where(arr % 2 != 0, -1, arr)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. Замените все элементы в массиве NumPy больше 30 или меньше 5 новым значением 10 

In [122]:
arr = np.array([0, 1, 20, 3, 4, 5, 6, -7, 8, 90])
print(arr)

[ 0  1 20  3  4  5  6 -7  8 90]


In [120]:
arr = np.where((arr > 30) | (arr < 5), 10, arr)
print(arr)

[10 10 20 10 10  5  6 10  8 10]


20. Отсортируйте двумерный массив по столбцам

In [125]:
a = np.array([[11,5,3], 
 [4,15,6], 
 [7,8,19]])
print(a)

[[11  5  3]
 [ 4 15  6]
 [ 7  8 19]]


In [126]:
sort_a = np.sort(a, axis=0)
print(sort_a)

[[ 4  5  3]
 [ 7  8  6]
 [11 15 19]]
